---
author: "Jennifer Mizhquiri Barbecho"
title: "Homework 2: Data Wrangling 1"
output: github_document
---

```{r setup}
library(tidyverse)
```

## Read in some data

Read in the trashweels 2020 dataset.

```{r}
library(readxl)
trashwheels_data = read_excel("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx")

trashwheels_data = janitor::clean_names(trashwheels_data)
```

## Take a look at the data

Printing in th console
```{r}
trashwheels_data
```

```{r, message =FALSE}
tail(trashwheels_data)
#note for later, December is misspelled "Decemeber"
```

## Clean 2018 Precipitation Data
```{r}
precip_2018_data = read_excel ("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
  sheet = "2018 Precipitation",skip = 1) %>% 
  janitor::clean_names() %>%
  mutate(year = 2018) %>% 
  drop_na()
  
```

## Clean 2019 Precipitation Data

```{r}
precip_2019_data = read_excel ("./data/Trash-Wheel-Collection-Totals-7-2020-2.xlsx", 
  sheet = "2019 Precipitation",skip = 1) %>% 
  janitor::clean_names() %>%
  mutate(year = 2019) %>% 
  drop_na()
```

